# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_betas <- function(design_full, lambda_mat, Ynorm) {
    .Call('_crescendo_solve_betas', PACKAGE = 'crescendo', design_full, lambda_mat, Ynorm)
}

merge_redundant_clusters <- function(R, thresh = 0.8) {
    .Call('_crescendo_merge_redundant_clusters', PACKAGE = 'crescendo', R, thresh)
}

solve_mu1 <- function(design_full, betas) {
    .Call('_crescendo_solve_mu1', PACKAGE = 'crescendo', design_full, betas)
}

solve_mu2 <- function(expected_logcounts_marginalized, R, sigmas, mu) {
    invisible(.Call('_crescendo_solve_mu2', PACKAGE = 'crescendo', expected_logcounts_marginalized, R, sigmas, mu))
}

#' @importFrom RcppParallel RcppParallelLibs
NULL

set_seed <- function(seed) {
    invisible(.Call('_crescendo_set_seed', PACKAGE = 'crescendo', seed))
}

draw_sample_cdf <- function(qmin, qmax, mu) {
    .Call('_crescendo_draw_sample_cdf', PACKAGE = 'crescendo', qmin, qmax, mu)
}

icdfpois_scalar <- function(k, mu_source, mu_target) {
    .Call('_crescendo_icdfpois_scalar', PACKAGE = 'crescendo', k, mu_source, mu_target)
}

parallelicdfPoisson <- function(k, mu_source, mu_target) {
    .Call('_crescendo_parallelicdfPoisson', PACKAGE = 'crescendo', k, mu_source, mu_target)
}

rcpparma_hello_world <- function() {
    .Call('_crescendo_rcpparma_hello_world', PACKAGE = 'crescendo')
}

rcpparma_outerproduct <- function(x) {
    .Call('_crescendo_rcpparma_outerproduct', PACKAGE = 'crescendo', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_crescendo_rcpparma_innerproduct', PACKAGE = 'crescendo', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_crescendo_rcpparma_bothproducts', PACKAGE = 'crescendo', x)
}

